name: Reset schedule

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * 0" # 일요일 11시

jobs:
  reset-schedule:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24

      - name: Install dependencies
        run: npx pnpm install

      - name: Reset schedule
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: npx tsx scripts/reset-schedule.ts
