name: Reset schedule

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * 0" # 일요일 11시

jobs:
  reset-schedule:
    runs-on: ubuntu-latest

    steps:
      - name: Github Repository 파일 불러오기
        uses: actions/checkout@v7

      - name: pnpm 설치 및 설정
        uses: pnpm/action-setup@v4

      - name: Node.js 설치 및 설정
        uses: actions/setup-node@v7
        with:
          node-version: current
          cache: "pnpm"

      - name: 의존성 설치
        run: pnpm install --frozen-lockfile

      - name: 근무표 초기화
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: node scripts/reset-schedule.js
